---
version: "3.5"
services:
  postgresql:
    container_name: temporal-postgresql
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    expose:
      - ${POSTGRES_DEFAULT_PORT}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - temporal-network

  temporal:
    container_name: temporal
    # use temporalio/auto-setup to automatically setup DB schema and namespaces
    # and start history service afterwards
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    depends_on:
      - postgresql
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap

  temporal-admin-tools:
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    networks:
      - temporal-network
    ports:
      - 8090:8080

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
